# api/config/api_platform/resources.yaml

resources:
    # App\Entity\Zone: ~
    # App\Entity\Champ: ~
    # App\Entity\Siteweb: ~
    # App\Entity\User: ~
    # App\Entity\Categorie: ~
    App\Entity\Contenu:
        attributes:
            normalization_context:
                groups: ['get', 'post']
            denormalization_context:
                groups: ['write']
